site_name: Astro Pi Orbit
site_description: Miscellaneous functions for use in the Astro Pi Mission Space Lab challenge
theme:
  name: material
  logo: images/astro-pi-logo.svg
  favicon: images/astro-pi-logo.svg
  features:
    - content.code.copy
nav:
  - Home: index.md
  - Recipes: recipes.md
  - API: api.md

markdown_extensions:
  # This configuration enables syntax highlighting on code blocks
  # and inline code blocks, and allows to include source code
  # directly from other files:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # This enables permalinks on headers, etc.
  - toc:
      permalink: true


